title: Andros RSS
description: My customised RSS feed
url: https://rss.andros.dev
output: index.xml
feeds:
  - https://educandogeek.github.io/podcast.xml
  - https://anchor.fm/s/443d308/podcast/rss
  
